### ISSUE TITLE
关于源码中prop_dis、lamb和pixel_size等具有单位的参数的疑问

### ISSUE THREAD

**Issue by jixiedy** [kqwang/DLPR#2]
尊敬的作者您好，
由于我刚开始学习全息，针对您的论文和代码，我有很多不明白的地方，能否请您允许我向您请教以下几个问题：
1.   您论文中提到：“ The propagation distance is set to 20 mm and 8.78 mm for the simulation comparisons and the experimental tests, respectively.”。对应的是您源码中的propagation函数中的prop_dis参数对么？prop_dis默认的是20毫米，prop_dis如果修改为8.78 mm或其他值，对应的lamb和pixel_size等是否也必须要进行相应的改变？比如，prop_dis=8.78 mm时，您实验时的lamb和pixel_size分别是多少？

2.   prop_dis、lamb和pixel_size等应该都有单位，您在论文中提到prop_dis的单位是毫米。在您的源码中，lamb = 632.8e-6，其中的632.8应该是632.8纳米吧，则632.8e-6对应的应该是毫米，对么？pixel_size = 8e-3，其中的8应该是8微米吧，8e-3对应的是8e-3毫米，对么？显然，对于这些带有单位的变量，您在源码中没有统一到国际标准单位米，那么与统一到国际单位米相比的话，最终的结果是否会有差异呢？

3.  我不使用氦氖激光器的632.8nm激光波长，而是替换为白光、绿光、蓝光、近红外光等其他光波的话，prop_dis就不适合再用您源码中的mm为单位的值，而是需要调整为以米为单位的值，对么？请问若替换为上述光波的话，则prop_dis的合理取值范围是多少呢？比如10m~50m左右是否合理？此时，pixel_size是否也不再适合选择8微米，而是应该修改为更小的取值，比如5微米？

希望我的上述问题，能得到您的阅读与解答。不胜感激！
祝好，

**Comment by kqwang** [comment]
非常荣幸该工作能得到您的关注。希望如下回答会对您有所帮助。
1. prop_dis，lamb和pixel_size 三者是相互独立的参数设置，互不影响。
2. 如您所见，代码中将毫米作为统一的标准单位。最终结果不受影响，只需乘以e3即可转换为国际标准单位：米。
3. 无论用什么标准长度单位，只要保证全局统一即可。理论上本代码仅适用于相干光源（单色光）。关于prop_dis的适用范围，取决于所使用的数值传播方程（给您推荐一篇[参考文献](https://doi.org/10.1364/JOSAA.401908) ) 。如1中所述，pixel_size的设置与prop_dis相互独立。
